### ISSUE TITLE
self-hosted runner 리서치

### ISSUE THREAD

**Issue by hyeseung-of-dable** [teamdable/vv-deploy-actions#20]
### AS-IS)
github에서 제공하는 cloud runner 사용
(-) private pip 라이브러리 설치하기 위해, parameter로 extra-index-url , trusted-host를 제공해야함 ( 보안 이슈 ? )
팀에서 사용하는 private pip 라이브러리 
- slackboy
- edge-info
- configargparse

(-) CI를 할 때도, GPU가 없어서 제한적임

### TO-BE)

**Comment by hyeseung-of-dable** [comment]
# Self-hosted runners 

## Level
- repository-level
- organization-level: 복수개의 레포에서 활용 가능 ⭐ 
owner가 발급한 token이 필요
- enterprise-level

**Comment by jingu-lee** [comment]
@hyeseung-of-dable self-hosted runner를 github actions로 연결할 때 장점 갑자기 생각이 났는데, CI와 branch protect 등에 활용될 것 같아서 좋아보입니다.

**Comment by hyeseung-of-dable** [comment]
# github hosted runner 사용 with docker

**Comment by hyeseung-of-dable** [comment]
# actions runner

self-hosted 장비(온프레미스 or 클라우드)를 러너머신으로 사용
-> actions 탭에서 workflows를 트리거하면 어디서 작업이 실행?

i. runner machine에서 직접 실행 
ii. Docker contatiner에서 실행

**Comment by hyeseung-of-dable** [comment]
# 어떤 장비를 actions runner로 사용하면 좋을까?

현재 2022-03-15) 오피스 2번 장비로 하는 중. 

1. CI
gpu가 있어야, ml 프로세서의 unittest가 가능해짐
-> 필요한 때에 g4dn.xlarge aws 인스턴스 생성 or 오피스 장비 이용

2. CD
cpu만 있어도 가능함. 비교적 단순한 작업을 실행
-> aws의 프리티어 인스턴스 사용하는 것이 어떤지?
( 1번장비는 테스트 장비로 환경이 일정하지않고, 재부팅이 잦음
2번장비는 장애 발생시, 대체할 수 있는 장비임. )
