### ISSUE TITLE
restart-actions에서 ${process-name} 변수 못읽어오는 오류

### ISSUE THREAD

**Issue by hyeseung-of-dable** [teamdable/vv-deploy-actions#28]
```
spawn /usr/bin/ssh -o StrictHostKeyChecking=no ${user}@${hostname} . /etc/profile; start-
Password:

Verification code:
```
${process-name} 변수를 받아오지못하는 것 같습니다!

https://github.com/teamdable/vv-deploy-test/runs/5493143462?check_suite_focus=true 에서 확인 가능

**Comment by yunseung-dable** [comment]
secrets 확인이 필요합니다! 
명령어 실행시 [secrets 관련 변수들이 입력되지 않은것을](https://github.com/teamdable/vv-deploy-test/runs/5493143462?check_suite_focus=true#step:8:4) 확인했습니다
때문에 password 인자로 process-name이 들어가며 password 재확인하는 작업과 동시에 permission denied가 발생한것 같습니다

**Comment by hyeseung-of-dable** [comment]
전에 세션할떄 사용했던 레포라서 secrets는 설정되어있어요! 
permission denied는 별개의 문제이고, 해당 이슈는 `. /etc/profile; start-` 명령어가 이렇게 출력되는 문제입니다!!

**Comment by hyeseung-of-dable** [comment]
@yunseung-dable 
전에 세션할떄 사용했던 레포라서 secrets는 설정되어있어요! 
permission denied는 별개의 문제이고, 해당 이슈는 `. /etc/profile; start-` 명령어가 이렇게 출력되는 문제입니다!!

**Comment by yunseung-dable** [comment]
이 [링크](https://github.com/teamdable/vv-deploy-test/runs/5493143462?check_suite_focus=true#step:8:4)의 커맨드를 보시면
입력인자로 user(1) 와 process-name(2) 두개만 전달되었는데요
때문에 [(4)번째 인자로 전달받기로한 ](https://github.com/teamdable/vv-deploy-actions/blob/698ae2a85cb31fe9af08b37d65e9d21dac127c44/.github/workflows/restart-process-after-deploy.yml#L67)process-name은 값이 없어서 `start-`로만 되어있습니다 
또한 password 인자에 process-name이 들어갔기때문에 password를 계속 재확인 하는것 같습니다!

**Comment by yunseung-dable** [comment]
[여기 변수명](https://github.com/teamdable/vv-deploy-test/blob/f7f70ddab361a4c4becbcf73cd2834f480a6a34e/.github/workflows/restart.yml#L25)이 secret 에 등록된것과 달라서 못찾은것 같아요!

**Comment by hyeseung-of-dable** [comment]
와 👍 vv-deploy-actions에 변수명을 일반적인(?)이름으로 해놨는데, 
제 스스로 낚였네요...
감사합니다 !!!!!!!!! 해결 완!!!!
