### ISSUE TITLE
restart actions를 했는데 프로세스가 시작되지 않음

### ISSUE THREAD

**Issue by yongja-jayong** [teamdable/vv-deploy-actions#35]
1. 프로세스모니터링에서 [이렇게 restart 액션을 적용시킴](https://github.com/teamdable/vv-process-monitoring/blob/main/.github/workflows/restart.yml)
2. [actions는 성공함](https://github.com/teamdable/vv-process-monitoring/runs/5565715699?check_suite_focus=true) (13, 17호기에 배포)
3. 그런데 직접 장비에 들어가서 확인해보니 process-moniotring이 돌아가고 있지 않음
4. vv-syslog에 남은 것 없음
5. nohup을 확인해보니 이런 로그가 남음 (아마 python 진입 전에 실패해서 syslog가 남지 않은듯)
```failed to run command 'python': No such file or directory```

**Comment by yongja-jayong** [comment]
관련이 있는지는 모르겠지만 에러메시지는 이 [이슈](https://github.com/teamdable/vv-edge-setup/issues/206)와 같음

**Comment by yunseung-dable** [comment]
슬랙논의로 다들 알겠지만 아카이빙겸 다시 공유드립니다
현재 조치는 파이썬 start-.. 스크립트 내에 환경을 직접 절대경로로 특정하는 방법으로 해두었습니다(vv-edge-setup==1.7.0)
