### ISSUE TITLE
배포시 발생하는 알람 줄이는 방법 고민

### ISSUE THREAD

**Issue by yongja-jayong** [teamdable/vv-deploy-actions#39]

**Comment by hyeseung-of-dable** [comment]
AS-IS)
process가 떠있는 상태에서, 배포
-> 배포가 완료되면, restart workflows로 재시작함

배포 시작 ~ 재시작 전까지, 프로세스가 제대로 작동하지않기도 함

TO-BE)

- 배포 시작 전에, kill process하고, 배포 후에 다시 start?

**Comment by hyeseung-of-dable** [comment]
solved
