### ISSUE TITLE
배포가 완료되면 성공/실패 여부를 슬랙으로 전송하기

### ISSUE THREAD

**Issue by hyeseung-of-dable** [teamdable/vv-deploy-actions#5]
v1.0.3에서 추가 예정

**Comment by hyeseung-of-dable** [comment]
슬랙으로 전송하는 방법
1. [slackboy](https://github.com/teamdable/vv-slackboy)를 사용
runner에 라이브러리 설치하기 위한 설정들이 필요함
질문) https://github.com/teamdable/vv-slackboy#%EC%84%A4%EC%B9%98%EB%B0%A9%EB%B2%95 설치 순서 변경이 필요할 듯. cfg에 들어가는 토큰은 어디서?


2. [slack으로 전송해주는 actions를 활용](https://velog.io/@tigger/Github-Action-Slack%EA%B3%BC-%EC%97%B0%EB%8F%99%ED%95%B4%EC%84%9C-%EB%B9%8C%EB%93%9C-%EA%B2%B0%EA%B3%BC-%EB%B0%9B%EA%B8%B0)
또 다른 api 웹훅 봇이 생김

**Comment by dongwook-of-dable** [comment]
1번
- token은 파라미터로도 전달 가능해야! 할 것 같습니다, 
- runner 에 라이브러리 설치는 판단되지 않는데, 전체 구성을 생각하면 [self hosted action](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#requirements-for-self-hosted-runner-machines) 같은 것도 살펴봐야하나 싶네요

**Comment by yunseung-dable** [comment]
1. token만으로 보낼수있도록 반영
2. 설치순서 보강
