### ISSUE TITLE
5번 장비에 코드 배포

### ISSUE THREAD

**Issue by yongja-jayong** [teamdable/vv-deploy-actions#54]
**DUE DATE : 목**
[관련슬랙](https://dable.slack.com/archives/C01163RRG8M/p1648543363947139)

- [x] inference
- [x] resource monitoring
- [x] process monitoring 1.0.2rc2
- [x] edge-setup
- [x] edge-player

**Comment by jingu-lee** [comment]
edge-setup, 혜승님 작업분(각 장비들 version 체크 cli) 이후 main merge 후 배포될 예정
inference, 완료
