### ISSUE TITLE
3, 4번 장비에 main branch 배포

### ISSUE THREAD

**Issue by yongja-jayong** [teamdable/vv-deploy-actions#72]
3, 4번 장비에 main branch 배포

# 3번 
### 원격 작업
- [x] [ssh otp 설정](https://dable.slack.com/archives/C01163RRG8M/p1642990080013800?thread_ts=1642751234.036700&cid=C01163RRG8M)
  - [x] .google_authenticator 파일 복사해두기
  - [x] 보안 설정
- [x] visudo (/etc/sudoers)경로 수정
- [x] ~/.bashrc, /etc/profile 확인&경로 수정
- [x] .git & .ssh key들 삭제
- [x] pyenv global edge-setup
- [x] pyenv inference 재설치 (inference용 requirements.txt로)
- [x] gpu driver auto update 방지
```
# done
vim /etc/apt/apt.conf.d/20auto-upgrades 

# done
sudo apt-mark hold nvidia-compute-utils-470 nvidia-dkms-470 nvidia-driver-470 nvidia-kernel-common-470 nvidia-kernel-source-470 nvidia-prime nvidia-settings nvidia-utils-470
```
-> 이후 코드배포

- [x] vv-edge-setup
  - [x] pyenv 재설치
- [x] vv-yolor
- [x] edge-player
- [x] process
- [x] resource

### 직접 가서 작업해야 하는 것
- [x] [팬 전선 제대로 꽂기](https://github.com/orgs/teamdable/projects/4#card-75160845)
- [x] [와이파이 온도 모듈 체크](https://github.com/teamdable/vv-resource-monitoring/issues/37) - 와이파이 켜두기
- [x] USB(3,4호기), 유선랜(4호기) 연장선 연결 안 되어 있는지 확인필요
- [x] 전원이 들어오면 자동으로 켜질 수 있도록 AC power on 설정
- [ ] 스피커 테스트

# 4번 
### 원격 작업
- [x] [ssh otp 설정](https://dable.slack.com/archives/C01163RRG8M/p1642990080013800?thread_ts=1642751234.036700&cid=C01163RRG8M)
  - [x] .google_authenticator 파일 복사해두기
  - [x] 보안 설정
- [x] visudo (/etc/sudoers)경로 수정
- [x] ~/.bashrc, /etc/profile 확인&경로 수정
- [x] .git & .ssh key들 삭제
- [x] pyenv global edge-setup
- [x] edge-setup pyenv 재설치
- [x] pyenv inference 재설치 (inference용 requirements.txt로)
- [x] gpu driver auto update 방지
```
#done
vim /etc/apt/apt.conf.d/20auto-upgrades

#done
sudo apt-mark hold nvidia-compute-utils-470 nvidia-dkms-470 nvidia-driver-470 nvidia-kernel-common-470 nvidia-kernel-source-470 nvidia-prime nvidia-settings nvidia-utils-470
```

-> 이후 코드배포

- [x] vv-edge-setup
  - [x] pyenv 재설치
- [x] vv-yolor
- [x] edge-player
- [x] process
- [x] resource

### 직접 가서 작업해야 하는 것
- [x] [팬 전선 제대로 꽂기](https://github.com/orgs/teamdable/projects/4#card-75160845)
- [x] USB(3,4호기), 유선랜(4호기) 연장선 연결 안 되어 있는지 확인필요
- [x] 전원이 들어오면 자동으로 켜질 수 있도록 AC power on 설정
- [x] 스피커 테스트

**Comment by jingu-lee** [comment]
git 삭제를 마지막에 하면 어떨까요? 우선 패치를 받아오는 방식이 더 빠르게 작업할 수 있을 것 같아서요

**Comment by yongja-jayong** [comment]
이슈
- 3호기: 스피커 볼륨을 max로 해놓고 연결 해놓았으나 소리가 안 난 다고함. 0으로 다시 세팅해 둠

**Comment by yongja-jayong** [comment]
감격의 close~!
