### ISSUE TITLE
xorg 100% 현상 디버깅을 위해 테스트 기기에 최신 코드 배포

### ISSUE THREAD

**Issue by yongja-jayong** [teamdable/vv-deploy-actions#73]
999호기 & 1호기에 최신 코드(develop or main) 배포
[참고 슬랙](https://dable.slack.com/archives/C01163RRG8M/p1651475268184709)
- [x] 프로세스 모니터링
- [x] 리소스 모니터링
- [x] vv-edge-setup (1.0.19 1번 ✅ 999번 ✅  )
- [x] edge-player
- [x] inference (1.0.4)
- [x] 모든 코드 배포 후, 모든 프로세스 재시작해서 돌려 놓기

**Comment by jingu-lee** [comment]
edge-setup은 현재 main에 있는 것 까지만 배포하면 되겠지요?
