### ISSUE TITLE
restart action 시작시 슬랙으로 알려주기

### ISSUE THREAD

**Issue by yongja-jayong** [teamdable/vv-deploy-actions#77]

**Comment by hyeseung-of-dable** [comment]
AS-IS) 
- 배포: 배포내에 `kill - deploy - start` 3단계가 포함되어서, 처음부터 알람이 옴.
- 프로세스 재시작만 할때: start-process.sh, kill-process.sh에서 종료될때만 슬랙 알람이 옴 -> 시작할 때도 알람오도록 수정 필요
